/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerdictPredictionIdRouteImport } from './routes/verdict.$predictionId'
import { Route as ProofPredictionIdRouteImport } from './routes/proof.$predictionId'
import { Route as ProfileWalletRouteImport } from './routes/profile.$wallet'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as AdminResultsRouteImport } from './routes/admin.results'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerdictPredictionIdRoute = VerdictPredictionIdRouteImport.update({
  id: '/verdict/$predictionId',
  path: '/verdict/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofPredictionIdRoute = ProofPredictionIdRouteImport.update({
  id: '/proof/$predictionId',
  path: '/proof/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/$wallet',
  path: '/$wallet',
  getParentRoute: () => ProfileRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/results': typeof AdminResultsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/proof/$predictionId': typeof ProofPredictionIdRoute
  '/verdict/$predictionId': typeof VerdictPredictionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/results': typeof AdminResultsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/proof/$predictionId': typeof ProofPredictionIdRoute
  '/verdict/$predictionId': typeof VerdictPredictionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/results': typeof AdminResultsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/proof/$predictionId': typeof ProofPredictionIdRoute
  '/verdict/$predictionId': typeof VerdictPredictionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/how-it-works'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/vault'
    | '/admin/results'
    | '/matches/$matchId'
    | '/profile/$wallet'
    | '/proof/$predictionId'
    | '/verdict/$predictionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/how-it-works'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/vault'
    | '/admin/results'
    | '/matches/$matchId'
    | '/profile/$wallet'
    | '/proof/$predictionId'
    | '/verdict/$predictionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/how-it-works'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/vault'
    | '/admin/results'
    | '/matches/$matchId'
    | '/profile/$wallet'
    | '/proof/$predictionId'
    | '/verdict/$predictionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  VaultRoute: typeof VaultRoute
  ProofPredictionIdRoute: typeof ProofPredictionIdRoute
  VerdictPredictionIdRoute: typeof VerdictPredictionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verdict/$predictionId': {
      id: '/verdict/$predictionId'
      path: '/verdict/$predictionId'
      fullPath: '/verdict/$predictionId'
      preLoaderRoute: typeof VerdictPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$predictionId': {
      id: '/proof/$predictionId'
      path: '/proof/$predictionId'
      fullPath: '/proof/$predictionId'
      preLoaderRoute: typeof ProofPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$wallet': {
      id: '/profile/$wallet'
      path: '/$wallet'
      fullPath: '/profile/$wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminResultsRoute: typeof AdminResultsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResultsRoute: AdminResultsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface ProfileRouteChildren {
  ProfileWalletRoute: typeof ProfileWalletRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileWalletRoute: ProfileWalletRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchesRoute: MatchesRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  VaultRoute: VaultRoute,
  ProofPredictionIdRoute: ProofPredictionIdRoute,
  VerdictPredictionIdRoute: VerdictPredictionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
